### ISSUE TITLE
Questions about your godog implementation

### ISSUE THREAD

**Issue by mxygem** [matt-simons/memcached-operator#5]
Heya!

I'm a contributor on godog and I ran across this repo trying to find ways to hook into go's type `T` with godog to explore possibly using testify in a suite.

I've noticed that you're setting up the main godog settings in `main_test.go`'s `TestMain` but then you're actually running it in `features_test.go`'s `TestLifecycleFeatures` function which is taking in testing's `T` type.

Could you help me understand how `TestLifecycleFeatures` is being called and how things run overall?

Thanks!

Js

**Comment by matt-simons** [comment]
Hey there,

This was a little hack so that I could switch between different paths for each Test (though most of that logic is removed as I created this repo for a workshop I ran), but I needed the operator test framework to already be setup. The real magic happens in their framework when I call `framework.MainEntry(m)` which starts up this operator and then eventually calls `m.Run()` https://github.com/operator-framework/operator-sdk/blob/master/pkg/test/framework.go#L254 which would also call all the other tests, if there were any.

p.s. Thanks for contributing to godog, I'm really enjoying using it :)

**Comment by mxygem** [comment]
Ah, gotcha! Do you have any sort of example or idea that'd accomplish what I'm trying without the operator sdk?

Also, absolutely! :)

**Comment by matt-simons** [comment]
Not sure I fully understand how you're looking to hook into T. My best guess is you could access it from the running steps if `StepHandler` is a function as a field in a struct which has `T`, something along the lines of: 

```
type Step struct {
        T *testing.T
}

func (s *Step) iCreateAResource(manifest *gherkin.DocString) error {
        // do the step
        s.T.Log("Something")
}

func RegisterSteps(s *godog.Suite, t *testing.T) {
        steps := Steps{
                Test: t
        }
	s.Step(`^I create a Resource:$`, steps.iCreateAResource)
}
```

I may have the complete wrong end of the stick here?

**Comment by mxygem** [comment]
We managed to get a setup provided to us so I'm good to go here. :) Thanks!
